-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Delivery"
(
    delivery_id integer NOT NULL,
    destination character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT "Delivery_pkey" PRIMARY KEY (delivery_id)
);

CREATE TABLE IF NOT EXISTS public."Food"
(
    food_id integer NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    CONSTRAINT "Food_pkey" PRIMARY KEY (food_id)
);

CREATE TABLE IF NOT EXISTS public."Food_Order"
(
    fo_id integer NOT NULL,
    food_id integer NOT NULL,
    order_id integer NOT NULL,
    CONSTRAINT "Food_Order_pkey" PRIMARY KEY (fo_id)
);

CREATE TABLE IF NOT EXISTS public."Order"
(
    order_id integer NOT NULL,
    order_date date NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT "Order_pkey" PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public."User"
(
    user_id integer NOT NULL,
    name character varying(55) COLLATE pg_catalog."default" NOT NULL,
    email character varying(55) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public."Delivery"
    ADD CONSTRAINT delivery2order FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Food_Order"
    ADD CONSTRAINT food2order FOREIGN KEY (food_id)
    REFERENCES public."Food" (food_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Food_Order"
    ADD CONSTRAINT order2food FOREIGN KEY (order_id)
    REFERENCES public."Order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order"
    ADD CONSTRAINT order2user FOREIGN KEY (user_id)
    REFERENCES public."User" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;